FROM dustynv/pytorch:2.6-r36.4.0-cu128

WORKDIR /workspaces

RUN \
    apt-get update && \
    apt-get install -y git && \
    apt-get install -y vim && \
    apt-get install -y libglib2.0-0 && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./src/container-prep/requirements-SmolLM2.txt ./requirements-SmolLM2.txt

RUN \
    pip install --upgrade pip && \
    pip install -r ./requirements-SmolLM2.txt && \
    pip install flash-attn --no-build-isolation

RUN \
    apt-get update && \
    apt-get install -y tesseract-ocr libtesseract-dev && \
    apt-get install -y libgtk-3-0  && \
    apt-get install -y libgstreamer-plugins-base1.0-0  && \
    apt-get install -y libtbb2 libtbb12  && \
    apt-get install -y libatlas-base-dev

RUN \
    pip install triton && \
    pip install pillow

CMD ["/bin/bash", "./src/entrypoint-SmolLM2.sh"]