FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

WORKDIR /workspaces

RUN \
    apt-get update && \
    apt-get install -y git && \
    apt-get install -y vim && \
    apt-get install -y libglib2.0-0 && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./src/container-prep/requirements-SmolLM2.txt ./requirements-SmolLM2.txt

RUN \
    pip install --upgrade pip && \
    pip install -r ./requirements-SmolLM2.txt && \
    pip install flash-attn --no-build-isolation


CMD ["/bin/bash", "./src/entrypoint-SmolLM2.sh"]