FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

WORKDIR /workspaces

RUN \
    apt-get update && \
    apt-get install -y git && \
    apt-get install -y vim && \
    apt-get install -y libglib2.0-0 && \
    apt-get install -y ffmpeg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./src /workspaces/src

RUN \
    pip install --upgrade pip && \
    pip install -r ./src/container-prep/requirements-videollama3.txt

CMD ["python", "./src/inference/inference-test-videollama3.py"]